fix: data persistence bug introduced in #2433 (#2460)
The Type Checking fix from #2433 introduced a new issue that causes an
error while persisting to the database.
This PR should fix that while passing mypy checks. 

    if not isinstance(self.storage_client, GCSStorageClient)
                                           ^^^^^^^^^^^^^^^^
NameError: name 'GCSStorageClient' is not defined. Did you mean:
'BaseStorageClient'?

---------

Co-authored-by: Josh Hayes <35790761+hayescode@users.noreply.github.com>